@echo off
setlocal enabledelayedexpansion

REM Find and call Visual Studio vcvars64.bat
set VCVARS_FOUND=0

for %%V in (2022 2019) do (
    if !VCVARS_FOUND! equ 0 (
        set "VC_PATH=C:\Program Files\Microsoft Visual Studio\%%V\Community\VC\Auxiliary\Build\vcvars64.bat"
        if exist "!VC_PATH!" (
            echo Initializing Visual Studio %%V...
            call "!VC_PATH!"
            set VCVARS_FOUND=1
            goto vcvars_done
        )
    )
    if !VCVARS_FOUND! equ 0 (
        set "VC_PATH=C:\Program Files\Microsoft Visual Studio\%%V\Professional\VC\Auxiliary\Build\vcvars64.bat"
        if exist "!VC_PATH!" (
            echo Initializing Visual Studio %%V...
            call "!VC_PATH!"
            set VCVARS_FOUND=1
            goto vcvars_done
        )
    )
    if !VCVARS_FOUND! equ 0 (
        set "VC_PATH=C:\Program Files (x86)\Microsoft Visual Studio\%%V\Community\VC\Auxiliary\Build\vcvars64.bat"
        if exist "!VC_PATH!" (
            echo Initializing Visual Studio %%V...
            call "!VC_PATH!"
            set VCVARS_FOUND=1
            goto vcvars_done
        )
    )
)

:vcvars_done
if !VCVARS_FOUND! equ 0 (
    echo [ERROR] Could not find Visual Studio. Install VS 2019 or 2022.
    pause
    exit /b 1
)

echo.
echo [sarn] Configuring CMake...
echo.

REM Clang-cl uses the MSVC ABI and needs the Windows SDK environment above.
where clang-cl >nul 2>&1
if !ERRORLEVEL! neq 0 (
    echo [ERROR] clang-cl was not found on PATH.
    echo Install LLVM or add its bin directory to PATH.
    pause
    exit /b 1
)
set "CLANG_CL=C:\LLVM\bin\clang-cl.exe"
if not exist "!CLANG_CL!" (
    echo [ERROR] Expected Clang at !CLANG_CL! was not found.
    pause
    exit /b 1
)

set "MT_PATH="
for /f "delims=" %%M in ('where mt 2^>nul') do if not defined MT_PATH set "MT_PATH=%%M"
if not defined MT_PATH (
    echo [ERROR] Windows SDK mt.exe was not found after loading Visual Studio.
    pause
    exit /b 1
)

REM Remove only generator metadata when switching from the old Visual Studio tree.
if exist build\CMakeCache.txt (
    findstr /C:"CMAKE_GENERATOR:INTERNAL=Ninja" build\CMakeCache.txt >nul 2>&1
    if !ERRORLEVEL! neq 0 (
        echo [sarn] Removing the old Visual Studio CMake cache...
        del /q build\CMakeCache.txt >nul 2>&1
        if exist build\CMakeFiles rmdir /s /q build\CMakeFiles
    )
)

echo [sarn] Using clang-cl with Ninja...
cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=!CLANG_CL! -DCMAKE_CXX_COMPILER=!CLANG_CL! "-DCMAKE_MT=!MT_PATH!" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DLLVM_DIR=C:/vcpkg/installed/x64-windows/share/llvm -DLLVM_ROOT=C:/vcpkg/installed/x64-windows -Draylib_DIR=C:/vcpkg/installed/x64-windows/share/raylib

if !ERRORLEVEL! neq 0 (
    echo [ERROR] CMake configuration failed!
    pause
    exit /b 1
)

echo.
echo [sarn] Building...
cmake --build build --parallel

if !ERRORLEVEL! neq 0 (
    echo [ERROR] Build failed.
    pause
    exit /b 1
)

(
    echo # Generated by cmake_configure.bat. Paths may be edited when moving the toolchain.
    echo llvm_bin=C:\LLVM\bin
    echo runtime_lib=%CD%\build\runtime\sarn.lib
    echo raylib_lib=C:\vcpkg\installed\x64-windows\lib\raylib.lib
    echo raylib_dll=C:\vcpkg\installed\x64-windows\bin\raylib.dll
    echo runtime_bin=C:\vcpkg\installed\x64-windows\bin
) > sarn.config
echo [sarn] Saved compiler paths to sarn.config

echo.
echo ================================================================
echo   BUILD SUCCESSFUL!
echo ================================================================
echo.
if exist "build\compiler\Release\sarnc.exe" (
    echo Compiler: build\compiler\Release\sarnc.exe
) else if exist "build\compiler\sarnc.exe" (
    echo Compiler: build\compiler\sarnc.exe
)
echo.
echo Test with: .\sarn.exe run sarn\examples\...
echo.
pause


